### ISSUE TITLE
Adding a duplicate torrent does not return an error anymore

### ISSUE THREAD

**Issue by michaeljoser** [FLYBYME/node-transmission#22]
When adding a duplicate torrent, no error is triggered. It just says that it is added ok but its not in the queue.

Further investigation revealed this with transmission 2.82+ 

https://trac.transmissionbt.com/ticket/5614

Not sure how to deal with this in our node.js code. Hope you can help :)

**Comment by angelxmoreno** [comment]
Testing on Transmission 2.9.2 for OSX. The client, web interface and this lib show no error but also do not create duplicate entries when adding a torrent that already exists. 

Safe to close this?

**Comment by FLYBYME** [comment]
Yeah I think it's safe to close.
