### ISSUE TITLE
Add torrent-rename-path support

### ISSUE THREAD

**Issue by Farbdose** [FLYBYME/node-transmission#35]
Would it be possible to add support for the `torrent-rename-path` function of the rpc interface, so that one can change the (display) name of a torrent?

**Comment by Farbdose** [comment]
Commit with patch: 1469211ed11df48b4c0e6df9873e0589ed2d0023 (work in progress)
Pull request incomming in the next days:
I couldn't test the code yet because I have to update transmission to V2.80 first.

**Comment by FLYBYME** [comment]
Hey thanks ill wait the pull.

**Comment by Farbdose** [comment]
...for some reason all files in https://download.transmissionbt.com/files/ return "nothing" atm
looks like this have to wait until monday / tuesday

**Comment by FLYBYME** [comment]
It's working for me. Just noticed they have a Windows build now.

**Comment by Farbdose** [comment]
I asked in the transmission IRC about it (they gave me link to an archiv mirror) maybe they already fixed it.
