### ISSUE TITLE
Rename torrent

### ISSUE THREAD

**Issue by FrancoisLef** [FLYBYME/node-transmission#40]
Hi, i'm facing an issue while renaming a torrent.

I've tried with differents settings.

My function here :
`transmission.rename(data.id, data.path, data.name, function() {
		// Callback
});`

What i tried to inject :
`{ id: 55,
  path: '/var/lib/transmission-daemon/downloads/debian-8.6.0-amd64-CD-2.iso',
  name: '/var/lib/transmission-daemon/downloads/debian-8.6.0-amd64-CD-2.isoadazd' }`

OR

`{ id: 55,
  path: '/var/lib/transmission-daemon/downloads/debian-8.6.0-amd64-CD-2.iso',
  name: 'debian-8.6.0-amd64-CD-2.isoazd' }`

OR

`{ id: 55,
  path: '/var/lib/transmission-daemon/downloads/',
  name: 'debian-8.6.0-amd64-CD-2.isoazdadad' }`

But file's name doesn't change :
`/var/lib/transmission-daemon/downloads`
`-rw-r--r-- 1 debian-transmission 629M sept. 20 02:19 debian-8.6.0-amd64-CD-1.iso`
`-rw-r--r-- 1 debian-transmission 648M sept. 20 02:24 debian-8.6.0-amd64-CD-2.iso`
`-rw-r--r-- 1 debian-transmission 648M sept. 20 02:22 debian-8.6.0-amd64-CD-3.iso`
`-rw-r--r-- 1 debian-transmission 583M sept. 20 02:24 debian-8.6.0-amd64-CD-4.iso`

I can't figure out why nothing is happening. No errors or output.
Can you help me ?

Otherwise, i successfully used `move` function.

Great job and thank you.

**Comment by FLYBYME** [comment]
I have not look at the project in some time, Il will have to take a look and see what the problem is.

Ill let you know.
Thanks for using.

**Comment by FrancoisLef** [comment]
I found where the problem was.
My path was not correct.

Thank you
